import nodemailer from 'nodemailer';
import { EmailData, ConversationContext, ProjectDetails } from '../types';

class EmailService {
  private transporter: nodemailer.Transporter;
  private readonly TO_EMAIL = process.env.MAIL_TO || 'shahasanepriyanka@gmail.com';

  constructor() {
    const mailUser = process.env.MAIL_USER;
    const mailPass = process.env.MAIL_PASS;

    if (!mailUser || !mailPass) {
      throw new Error('MAIL_USER and MAIL_PASS are required in environment variables');
    }

    this.transporter = nodemailer.createTransport({ 
      service: 'gmail',
      auth: {
        user: mailUser,
        pass: mailPass,
      },
    });
  }

  private formatProjectDetails(projectDetails: ProjectDetails): string {
    const details: string[] = [];
    
    if (projectDetails.clientName) {
      details.push(`<strong>Client Name:</strong> ${projectDetails.clientName}`);
    }
    if (projectDetails.designation) {
      details.push(`<strong>Designation:</strong> ${projectDetails.designation}`);
    }
    if (projectDetails.companyName) {
      details.push(`<strong>Company:</strong> ${projectDetails.companyName}`);
    }
    if (projectDetails.phoneNumber) {
      details.push(`<strong>Phone:</strong> ${projectDetails.phoneNumber}`);
    }
    if (projectDetails.email) {
      details.push(`<strong>Email:</strong> ${projectDetails.email}`);
    }
    if (projectDetails.projectIdea) {
      details.push(`<strong>Project Idea:</strong> ${projectDetails.projectIdea}`);
    }
    if (projectDetails.timeline) {
      details.push(`<strong>Timeline:</strong> ${projectDetails.timeline}`);
    }
    if (projectDetails.budget) {
      details.push(`<strong>Budget:</strong> ${projectDetails.budget}`);
    }
    if (projectDetails.additionalInfo) {
      details.push(`<strong>Additional Info:</strong> ${projectDetails.additionalInfo}`);
    }

    return details.length > 0 ? details.join('<br>') : 'No project details collected';
  }

  private formatConversationTranscript(messages: any[]): string {
    if (messages.length === 0) return 'No conversation history available';

    return messages.map(msg => {
      const time = new Date(msg.timestamp).toLocaleTimeString();
      const sender = msg.from === 'user' ? '👤 User' : '🤖 Assistant';
      return `<div style="margin-bottom: 10px;">
        <strong>${sender} (${time}):</strong><br>
        ${msg.text.replace(/\n/g, '<br>')}
      </div>`;
    }).join('');
  }

  private createEmailHTML(
    subject: string,
    projectDetails: ProjectDetails,
    conversationHistory: any[],
    reason: 'conversation_end' | 'calendly_booked'
  ): string {
    const calendlyStatus = projectDetails.calendlyBooked 
      ? '<span style="color: #28a745;">✅ Calendly meeting scheduled</span>'
      : '<span style="color: #ffc107;">⏳ Calendly meeting not yet scheduled</span>';

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <title>${subject}</title>
        <style>
          body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
          .container { max-width: 600px; margin: 0 auto; padding: 20px; }
          .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
          .section { background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 15px; }
          .section h3 { margin-top: 0; color: #495057; }
          .conversation { background: white; padding: 15px; border-radius: 8px; border-left: 4px solid #007bff; }
          .status { padding: 10px; border-radius: 5px; margin: 10px 0; }
          .footer { text-align: center; margin-top: 30px; color: #6c757d; font-size: 14px; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>🤖 AI Assistant Report</h1>
            <p>New ${reason === 'calendly_booked' ? 'Calendly Booking' : 'Conversation'} Summary</p>
          </div>

          <div class="section">
            <h3>📊 Summary</h3>
            <p><strong>Reason:</strong> ${reason === 'calendly_booked' ? 'Calendly meeting was scheduled' : 'Conversation ended'}</p>
            <p><strong>Session ID:</strong> ${conversationHistory[0]?.sessionId || 'Unknown'}</p>
            <p><strong>Status:</strong> ${calendlyStatus}</p>
          </div>

          <div class="section">
            <h3>📋 Project Details</h3>
            ${this.formatProjectDetails(projectDetails)}
          </div>

          <div class="section">
            <h3>💬 Conversation Transcript</h3>
            <div class="conversation">
              ${this.formatConversationTranscript(conversationHistory)}
            </div>
          </div>

          <div class="footer">
            <p>This email was automatically generated by Priyanka's AI Assistant</p>
            <p>Generated on ${new Date().toLocaleString()}</p>
          </div>
        </div>
      </body>
      </html>
    `;
  }

  async sendProjectSummary(
    conversationContext: ConversationContext,
    reason: 'conversation_end' | 'calendly_booked'
  ): Promise<boolean> {
    try {
      const subject = reason === 'calendly_booked' 
        ? '🎉 New Calendly Booking - Project Summary'
        : '📝 Conversation Summary - Project Details';

      const emailData: EmailData = {
        to: this.TO_EMAIL,
        subject,
        html: this.createEmailHTML(subject, conversationContext.projectDetails, conversationContext.messages, reason),
        text: this.createTextVersion(conversationContext, reason)
      };

      const info = await this.transporter.sendMail({
        from: process.env.MAIL_USER,
        to: emailData.to,
        subject: emailData.subject,
        html: emailData.html,
        text: emailData.text
      });

      console.log('📧 Email sent successfully:', info.messageId);
      return true;

    } catch (error) {
      console.error('❌ Email sending failed:', error);
      return false;
    }
  }

  private createTextVersion(
    conversationContext: ConversationContext,
    reason: 'conversation_end' | 'calendly_booked'
  ): string {
    const { projectDetails, messages } = conversationContext;
    
    let text = `AI Assistant Report\n`;
    text += `Reason: ${reason === 'calendly_booked' ? 'Calendly meeting scheduled' : 'Conversation ended'}\n`;
    text += `Session ID: ${conversationContext.sessionId}\n\n`;
    
    text += `Project Details:\n`;
    if (projectDetails.clientName) text += `Client Name: ${projectDetails.clientName}\n`;
    if (projectDetails.designation) text += `Designation: ${projectDetails.designation}\n`;
    if (projectDetails.companyName) text += `Company: ${projectDetails.companyName}\n`;
    if (projectDetails.phoneNumber) text += `Phone: ${projectDetails.phoneNumber}\n`;
    if (projectDetails.email) text += `Email: ${projectDetails.email}\n`;
    if (projectDetails.projectIdea) text += `Project Idea: ${projectDetails.projectIdea}\n`;
    if (projectDetails.timeline) text += `Timeline: ${projectDetails.timeline}\n`;
    if (projectDetails.budget) text += `Budget: ${projectDetails.budget}\n`;
    if (projectDetails.additionalInfo) text += `Additional Info: ${projectDetails.additionalInfo}\n`;
    
    text += `\nCalendly Status: ${projectDetails.calendlyBooked ? 'Scheduled' : 'Not scheduled'}\n\n`;
    
    text += `Conversation Transcript:\n`;
    messages.forEach(msg => {
      const time = new Date(msg.timestamp).toLocaleTimeString();
      const sender = msg.from === 'user' ? 'User' : 'Assistant';
      text += `${sender} (${time}): ${msg.text}\n`;
    });
    
    return text;
  }

  // Test email functionality
  async testConnection(): Promise<boolean> {
    try {
      await this.transporter.verify();
      console.log('✅ Email service connection verified');
      return true;
    } catch (error) {
      console.error('❌ Email service connection failed:', error);
      return false;
    }
  }
}

export const emailService = new EmailService();